services:
  test:
    build: ./backend
    working_dir: /app
    command: /bin/sh -c "pip install -r requirements-test.txt && python -m pytest -v tests/"
    environment:
      DATABASE_URL: "sqlite:///:memory:"
      SECRET_KEY: "test-secret-key"
    volumes:
      - ./backend/app:/app/app
      - ./backend/tests:/app/tests
      - ./backend/pytest.ini:/app/pytest.ini
      - ./backend/requirements-test.txt:/app/requirements-test.txt